### PR TITLE
Fixed build

### PR DESCRIPTION
**Pull request by mdanilov**
- created symlink README for README.md (autoconf required README file)
- add executable flag fro autogen.sh script
- added .gitignore

### CODE REVIEW

**Comment by mdanilov** [comment]
Regarding the org.genivi.persistence.admin.conf. I found that this file is not installed by any persistence-client-library or persistence-common-object packages, but it is required for DBUS communication. Also I saw that this file was removed from this repository by previous commit, because of BitbBake collision, but I think it was a confusion cause there are 2 Yocto recipes for persistence-client-library one in PCL repo and one in ivi-meta. First recipe has installation rules for org.genivi.persistence.admin.conf. 

I think this file should be installed by this package on Makefile level, and should be removed from PCL repo as a Yocto recipes to avoid confusion.

If you are agree I would like return it back. Because now if we trying to install this libraries using make (no BitBake) it will not work due to absence of Dbus config file.

Note: it will also requires to change bb recipes in meta-ivi

**Comment by jeremiah** [comment]
I think the meta-ivi maintainer @frznlogic is the best person to talk to about where the config file should be created.

**Comment by jeremiah** [comment]
bump @frznlogic

**Comment by frznlogic** [comment]
Hi, sorry, for some reason I ignored this repo in my mail :D. I shouldn't have apparently. Anyways, late answer. The commits are a bit weird tbh, you delete and re-add the files in subsequent files. I guess it's too late to fix this as it's already merged to master, but I think for the future, these commits should have been squashed into a single commit/removed entirely. 

As for the content changes I don't mind, I don't think it will change the behavior of the build for yocto either.

**Pull request merged**
